export const Users = [
    {
      id:1,
      profilePicture: "me_night.jpeg",
      username: "Isıl Bardakci",
    },
    {
      id:2,
      profilePicture: "profile.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "mepink.jpeg",
      username: "Alexa Durden",
    },
    {
      id:4,
      profilePicture: "oldButGold.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "art.jpg",
      username: "Friday Holden",
    },
    {
      id:6,
      profilePicture: "meon.jpeg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "me_short_hair.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "kitty.jpg",
      username: "Maria Kitty",
    },
    {
      id:9,
      profilePicture: "merose.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "me.jpg",
      username: "Kristen Thomas",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Atam izindeyiz",
      photo: "anitkabir.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc:"Isil isil her yer",
      photo: "light_show.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Heart in moment",
      photo: "leaf_heart.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "seasnail.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "kittens.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "nazilli.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: " 1 Cat 1 the R00t",
      photo: "catOnRoot.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "kitty.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Big brother is watching u 0.o",
      photo: "horoz.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "purple.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];